openapi: 3.0.0
info:
  title: API сервиса Lucky Insuranc
  description: >-
    Коллекция запросов API сервиса. Сервис предоставляет информацию об страховках для животных
  version: 1.0.1
  contact:
    name: LuckyFilms API
    url: https://lucky.com/info
    email: LuckyFilms@lucky.com
  termsOfService: https://lucky.com/terms
  license:
    name: license 1.0.1 Lucky
    url: https://lucky.com/license
servers:
  - url: https://4453f729-1913-49be-9dcc-b7a316afa17f.mock.pstmn.io
    description: # заполнить
tags:
  - name: # заполнить
paths:
  /insurance:
    # указать тип запроса
      tags:
        - # заполнить
      summary: Описание всех страховок для животных
      description: 
      operationId: insuranceList
      responses:
        '200':
          description: список страховок
          # дальше заполните пропуски там, где это необходимо
          content:
            application/json:
              schema:
                properties:
                  description:
                    type: 
                    description: 
                    example: Помощь ветеринара 24/7. Онлайн консультации. Большой выбор ветклиник.
                  insurances:
                    type: 
                    items:
                          $ref: '#/components/schemas/response_200'
        '400':
          description: 
        # укажите еще 2-3 типа ошибок 
components:
  schemas:
    response_200:
      required:
        - 
        - 
        -
      type: 
      properties:
        type: 
          type: 
          description:
          example: кошка
        details:
          type: 
          description: 
          example: Круглосуточные консультации ветеринарного врача по телефону, в чате или видеосвязи. Включена ежегодная вакцинация от бешенства.
        price:
          type: 
          description: 
          example: 50000
        currency:
          type: 
          description:
          example: 'рублей'
        period:
          type: 
          description:
          example: 'в год'