openapi: 3.0.0
info:
  title: API сервиса Lucky Insurance
  description: >-
    Коллекция запросов API сервиса. Сервис предоставляет информацию о страховках для животных
  version: 1.0.1
  contact:
    name: LuckyInsurance API #Бонус - контакт не соответствовал сервису, исправил
    url: https://lucky.com/info
    email: LuckyInsurance@lucky.com
  termsOfService: https://lucky.com/terms
  license:
    name: license 1.0.1 Lucky
    url: https://lucky.com/license
servers:
  - url: https://4453f729-1913-49be-9dcc-b7a316afa17f.mock.pstmn.io
    description: Postman Mock Server для тестирования API
tags:
  - name: Insurances
paths:
  /insurance:
    get:
      tags:
        - Insurances
      summary: Описание всех страховок для животных
      description: Возвращает список всех доступных страховок для животных. 
      operationId: insuranceList
      responses:
        '200':
          description: Список страховок
          # дальше заполните пропуски там, где это необходимо
          content:
            application/json:
              schema:
                type: object #ответ — JSON-объект; ниже есть properties, поэтому тип указываю явно
                properties:
                  description: 
                    type: string
                    description: Краткое описание преимуществ, отображаемое над списком страховок
                    example: Помощь ветеринара 24/7. Онлайн консультации. Большой выбор ветклиник.
                  insurances:
                    type: array
                    items:
                          $ref: '#/components/schemas/response_200'
        '400':
          description: Ошибка валидации параметров запроса
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервер временно недоступен
components:
  schemas:
    response_200:
      required:
        - type
        - details
        - price
        - currency
        - period
      type: object
      properties:
        type: 
          type: string
          description: Тип питомца
          example: кот # на макете именно кот
          enum: # включил дополнение
            - кот
            - собака
        details:
          type: string
          description: Основные условия страховки
          example: Круглосуточные консультации ветеринарного врача по телефону, в чате или видеосвязи. Включена ежегодная вакцинация от бешенства.
        price:
          type: integer
          description: Цена страховки
          example: 50000
        currency:
          type: string
          description: Валюта
          example: 'рублей'
        period: 
          type: string
          description: Период действия страховки
          example: 'в год'
